    Copyright (c) 2018
    Author: Chaitanya Tejaswi (github.com/CRTejaswi)    License: GPL v3.0+

# Practice - Python Modules

## Numpy

* [Arrays](https://www.hackerrank.com/challenges/np-arrays/problem)

In [18]:
# [1: Using list slicing & list comprehension]
import numpy as np
def arrays(X):
    return np.array([float(x) for x in X[::-1]])
X = input().strip().split(' ')
result = arrays(X)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [20]:
# [2: Using in-built function]
import numpy as np

X = input().strip().split(' ')
X = np.flip(X,0)
X = np.array([float(x) for x in X])
print(X)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


* [Shape and Reshape](https://www.hackerrank.com/challenges/np-shape-reshape/problem)

In [4]:
import numpy as np

X = input().strip().split(' ')
X = np.array([int(x) for x in X])
X.shape = (3,3)
print(X)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* [Transpose and Flatten](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem)

In [8]:
# [1: Read inputs as ints]
import numpy as np
X = []
n,m = input().strip().split(' ',maxsplit=1)
n,m = int(n),int(m)
while(n>0):
    X.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
X = np.array(X)
print(np.transpose(X),X.flatten(),sep='\n')

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
# [2: Read inputs as string, then convert to ints]
import numpy as np
X = []
n,m = input().strip().split(' ',maxsplit=1)
n,m = int(n),int(m)
while(n>0):
    X.append([x for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
X = np.array([[int(i) for i in x] for x in X])
print(np.transpose(X),X.flatten(),sep='\n')

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


* [Concatenate](https://www.hackerrank.com/challenges/np-concatenate/problem)

In [3]:
# [1a: Without np.concatenate(); Read inputs as ints]
import numpy as np
X = []
n,m,p = input().strip().split(' ',maxsplit=2)
n,m,p = int(n),int(m),int(p)
k=m+n
while(k>0):
    X.append([int(x) for x in input().strip().split(' ',maxsplit=p-1)])
    k-=1
X = np.array(X)
print(X)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [3]:
# [1b: Without np.concatenate(); Read inputs as string, then convert to ints]
import numpy as np
X = []
n,m,p = input().strip().split(' ',maxsplit=2)
n,m,p = int(n),int(m),int(p)
k=m+n
while(k>0):
    X.append([x for x in input().strip().split(' ',maxsplit=p-1)])
    k-=1
X = np.array([[int(i) for i in x] for x in X])
print(X)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [2]:
# [2: With np.concatenate(); Read inputs as ints] - Bad Code
import numpy as np
X1,X2 = [],[]
n,m,p = input().strip().split(' ',maxsplit=2)
n,m,p = int(n),int(m),int(p)

while(n>0):
    X1.append([int(x) for x in input().strip().split(' ',maxsplit=p-1)])
    n-=1
while(m>0):
    X2.append([int(x) for x in input().strip().split(' ',maxsplit=p-1)])
    m-=1
X1,X2 = np.array(X1),np.array(X2)
X = np.concatenate((X1,X2),axis=0)
print(X)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


* [Zeros and Ones](https://www.hackerrank.com/challenges/np-zeros-and-ones/problem)

In [1]:
# [: Using tuple to store dimensions]
import numpy as np
i,j,k = input().strip().split(' ',maxsplit=2)
i,j,k = int(i),int(j),int(k)
shape = (i,j,k)
print(np.zeros(shape,dtype=np.int),np.ones(shape,dtype=np.int),sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


* [Eye and Identity](https://www.hackerrank.com/challenges/np-eye-and-identity/problem)

In [7]:
# [: Using tuple to store dimensions]
import numpy as np
n,m = input().strip().split(' ',maxsplit=1)
n,m = int(n),int(m)
print(np.eye(n,m,k=0))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* [Array Mathematics](https://www.hackerrank.com/challenges/np-array-mathematics/problem)

In [16]:
# [1: Using operator overloading]
import numpy as np
A,B = [],[]
n,m = input().strip().split(' ',maxsplit=2)
n,m = int(n),int(m)
temp = n
while(n>0):
    A.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
n = temp
while(n>0):
    B.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
A = np.array(A)
B = np.array(B)
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [15]:
# [2: Using in-built functions]
import numpy as np
A,B = [],[]
n,m = input().strip().split(' ',maxsplit=2)
n,m = int(n),int(m)
temp = n
while(n>0):
    A.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
n = temp
while(n>0):
    B.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
A = np.array(A)
B = np.array(B)
print(np.add(A,B),np.subtract(A,B),np.multiply(A,B),np.floor_divide(A,B),\
      np.mod(A,B),np.power(A,B),sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


* [Floor, Ceil and Rint](https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem)

In [18]:
# [2: Using in-built functions]
import numpy as np
X = []
X.append([float(x) for x in input().strip().split(' ')])
X = np.array(X)
print(np.floor(X),np.ceil(X),np.rint(X),sep='\n')

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[[1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]]


* [Sum and Prod](https://www.hackerrank.com/challenges/np-sum-and-prod/problem)

In [24]:
# [2: Using in-built functions]
import numpy as np
X = []
n,m = input().strip().split(' ',maxsplit=1)
n,m = int(n),int(m)
while(n>0):
    X.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
X = np.array(X)
print(np.prod(np.sum(X,axis=0)))

2 2
1 2
3 4
24


* [Min and Max](https://www.hackerrank.com/challenges/np-min-and-max/problem)

In [23]:
# [2: Using in-built functions]
import numpy as np
X = []
n,m = input().strip().split(' ',maxsplit=1)
n,m = int(n),int(m)
while(n>0):
    X.append([int(x) for x in input().strip().split(' ',maxsplit=m-1)])
    n-=1
X = np.array(X)
print(np.max(np.min(X,axis=1)))

4 2
2 5
3 7
1 3
4 0
3
